version: 2
jobs:
  build_and_test:
    docker:
      - image: docker:18.09
    steps:
      - checkout
      - setup_remote_docker
      - run: apk add --no-cache --no-progress make
      - run: make light full
  build_test_and_deploy:
    docker:
      - image: docker:18.09
    steps:
      - checkout
      - setup_remote_docker
      - run: >-
          echo "$DOCKER_PASSWORD" |
            docker login --username "$DOCKER_USERNAME" --password-stdin
      - run: apk add --no-cache --no-progress make
      - run: make deploy
workflows:
  version: 2
  ci:
    jobs:
      - build_and_test:
          filters:
            branches:
              ignore: master
      - build_test_and_deploy:
          filters:
            branches:
              only: master
          context: "Docker Hub"
